# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy

# builds:
  # - id: "windows"
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
  #   main: main.go

  # - id: "linux_and_darwin"
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - linux
  #     - darwin
  #   goarch:
  #     # - "386"
  #     # - arm
  #     - amd64
  #     - arm64
  #   main: main.go

dockers:
  - goos: linux
    use: buildx
    skip_push: "false"
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
