name: Deploy to k8s

on: 
  page_build:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://be-friends.cjtim.com/api/v1
    steps:
      - name: Trigger deployment
        run: |
          curl -XPOST -u "${{ github.repository_owner }}:${{ secrets.PUSH_PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/cjtim/be-friends-deployment/dispatches \
          --data '{"event_type": "deploy-api"}'
