# This is a basic workflow to help you get started with Actions
name: release-tag
# Controls when the action will run.
on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.PUSH_PAT }}