name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: be-friends-api

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: gh-pages
          path: gh-pages
      
      - run: tree .

      - run: |
          echo ${PWD}
          cd be-friends-api
          echo "TAG: ${GITHUB_REF_NAME}"
          sed -i "s/version:.*/version: ${GITHUB_REF_NAME}/" helm/Chart.yaml
          sed -i "s/appVersion:.*/appVersion: \"${GITHUB_REF_NAME}\"/" helm/Chart.yaml

          helm package helm --destination ../gh-pages
          helm repo index ../gh-pages --url https://cjtim.github.io/be-friends-api

      - run: |
          echo ${PWD}
          cd gh-pages
          git config --local user.name "cjtim-bot"
          git config --local user.email "47479090+cjtim@users.noreply.github.com"
          git add -A
          git commit -m "Update helm chart ${GITHUB_REF_NAME}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_PAT }}
          branch: gh-pages
          path: gh-pages